package scaffold

import (
	"encoding/json"
	"fmt"
	"path"
	"sort"
	"strings"
)

// InstallSpec is the staging contract shipped as install.json in the bundle. The
// generated adapter reads it at startup and, for the asset(s) matching the host
// os/arch, fetches → sha256-verifies → stages under $APP/<exec_path> → runs any
// install args, in the resolved install order. It is the machine-readable form
// of the publisher's Artifacts step (R2 location + dependencies + order + args).
//
// Integrity: each asset carries its own sha256, and the whole bundle tarball is
// itself sha-pinned in the catalogue (bundle_sha256), so install.json cannot be
// altered without failing the install-time tarball check.
type InstallSpec struct {
	Schema  int            `json:"schema"`  // 1
	App     string         `json:"app"`     // io.pilot.<name>
	Version string         `json:"version"` // app_version
	Command string         `json:"command"` // base command the adapter execs (proc.exec target)
	Assets  []InstallAsset `json:"assets"`
}

// InstallAsset mirrors scaffold.Asset in the on-disk install spec. Order is the
// RESOLVED per-platform install sequence (0-based) after dependency sorting, so
// a consumer can simply install ascending-by-order within its platform.
type InstallAsset struct {
	Name     string   `json:"name"`
	Role     string   `json:"role"`      // binary | data
	OS       string   `json:"os"`        // linux | darwin
	Arch     string   `json:"arch"`      // amd64 | arm64
	URL      string   `json:"url"`       // https (R2 public URL)
	SHA256   string   `json:"sha256"`    // 64-hex of the downloaded object
	Unpack   string   `json:"unpack"`    // "" | "tar.gz"
	ExecPath string   `json:"exec_path"` // dest under $APP, or path inside the extracted tree
	Deps     []string `json:"deps"`      // names of same-platform assets installed first
	Order    int      `json:"order"`     // resolved install sequence within the platform
	Args     []string `json:"args"`      // optional post-stage invocation
}

// resolvedAssets returns every asset across all platforms, each platform's set
// dependency-ordered (Order set to the resolved 0-based sequence). The slice is
// grouped by platform and sorted (os, arch, order) so install.json/install.sh
// are deterministic.
func (c *Config) resolvedAssets() ([]InstallAsset, error) {
	var out []InstallAsset
	plats := c.assetPlatforms()
	sort.Slice(plats, func(i, j int) bool {
		if plats[i][0] != plats[j][0] {
			return plats[i][0] < plats[j][0]
		}
		return plats[i][1] < plats[j][1]
	})
	for _, p := range plats {
		seq, err := c.ResolveAssets(p[0], p[1])
		if err != nil {
			return nil, err
		}
		for i, a := range seq {
			role := a.Role
			if role == "" {
				role = "binary"
			}
			out = append(out, InstallAsset{
				Name: a.AssetName(), Role: role, OS: a.OS, Arch: a.Arch, URL: a.URL,
				SHA256: a.SHA256, Unpack: a.Unpack, ExecPath: path.Clean(a.ExecPath),
				Deps: a.Deps, Order: i, Args: a.Args,
			})
		}
	}
	return out, nil
}

// marshalInstallSpec builds install.json from cfg.Assets in resolved order.
func marshalInstallSpec(c *Config) ([]byte, error) {
	var cmd string
	if len(c.Backend.Command) > 0 {
		cmd = c.Backend.Command[0]
	}
	assets, err := c.resolvedAssets()
	if err != nil {
		return nil, err
	}
	spec := InstallSpec{Schema: 1, App: c.ID, Version: c.AppVersion, Command: cmd, Assets: assets}
	b, err := json.MarshalIndent(spec, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}

// renderInstallScript produces a standalone, dependency-free POSIX install.sh
// that performs the SAME install the adapter's stage.go does — fetch from R2,
// sha256-verify, stage under $APP (single file or tar.gz), run install args — in
// the resolved order, for the host's os/arch. It ships in the bundle for
// transparency and for hosts/operators that want to run the install directly
// (e.g. debugging, or a non-Go runtime). The adapter remains the default path.
func renderInstallScript(c *Config) ([]byte, error) {
	assets, err := c.resolvedAssets()
	if err != nil {
		return nil, err
	}
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format, a...); b.WriteByte('\n') }

	w("#!/usr/bin/env sh")
	w("# install.sh — GENERATED by pilot-app for %s %s.", c.ID, c.AppVersion)
	w("# Fetches this app's artifacts from the Pilot R2 registry, verifies each")
	w("# sha256, stages them under $APP, and runs any install steps — in dependency")
	w("# order. This mirrors the adapter's built-in staging (internal/backend/stage.go);")
	w("# either is sufficient. Usage: APP=/path/to/app sh install.sh")
	w("set -eu")
	w("")
	w(`APP="${APP:-$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)}"`)
	w(`OS="$(uname -s | tr '[:upper:]' '[:lower:]')"`)
	w(`ARCH="$(uname -m)"`)
	w(`case "$ARCH" in aarch64) ARCH=arm64;; x86_64) ARCH=amd64;; esac`)
	w(`echo "pilot-install: staging %s artifacts for ${OS}/${ARCH} into ${APP}"`, c.ID)
	w("")
	w("sha256_of() {")
	w(`  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | awk '{print $1}';`)
	w(`  else shasum -a 256 "$1" | awk '{print $1}'; fi`)
	w("}")
	w("")
	w("stage_one() { # url sha unpack exec_path role")
	w(`  url="$1"; want="$2"; unpack="$3"; exec_path="$4"; role="$5"`)
	w(`  tmp="$(mktemp)"`)
	w(`  echo "  fetch  $url"`)
	w(`  curl -fSL "$url" -o "$tmp"`)
	w(`  got="$(sha256_of "$tmp")"`)
	w(`  if [ "$got" != "$want" ]; then echo "  sha256 MISMATCH for $exec_path: want $want got $got" >&2; rm -f "$tmp"; exit 1; fi`)
	w(`  echo "  verify ok ($want)"`)
	w(`  if [ "$unpack" = "tar.gz" ]; then`)
	w(`    tar -xzf "$tmp" -C "$APP"; rm -f "$tmp"`)
	w(`  else`)
	w(`    dest="$APP/$exec_path"; mkdir -p "$(dirname -- "$dest")"; mv "$tmp" "$dest"`)
	w(`    if [ "$role" != "data" ]; then chmod 0755 "$dest"; fi`)
	w(`  fi`)
	w(`  echo "  staged $exec_path"`)
	w("}")
	w("")
	// Emit a guarded block per platform so one script serves every host.
	plats := map[string]bool{}
	var order []string
	for _, a := range assets {
		k := a.OS + "/" + a.Arch
		if !plats[k] {
			plats[k] = true
			order = append(order, k)
		}
	}
	for _, k := range order {
		os, arch, _ := strings.Cut(k, "/")
		w(`if [ "$OS" = "%s" ] && [ "$ARCH" = "%s" ]; then`, os, arch)
		for _, a := range assets {
			if a.OS != os || a.Arch != arch {
				continue
			}
			w(`  stage_one %q %q %q %q %q`, a.URL, a.SHA256, a.Unpack, a.ExecPath, a.Role)
			if len(a.Args) > 0 {
				w(`  echo "  run    %s %s"`, a.ExecPath, shJoin(a.Args))
				w(`  "$APP/%s" %s`, a.ExecPath, shJoin(a.Args))
			}
		}
		w(`  echo "pilot-install: done"; exit 0`)
		w(`fi`)
	}
	w(`echo "pilot-install: no artifact for ${OS}/${ARCH}" >&2; exit 1`)
	return []byte(b.String()), nil
}

// shJoin renders args as a single-quoted, space-joined POSIX argv fragment.
func shJoin(args []string) string {
	parts := make([]string, len(args))
	for i, a := range args {
		parts[i] = "'" + strings.ReplaceAll(a, "'", `'\''`) + "'"
	}
	return strings.Join(parts, " ")
}
